name: Ping Website

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  ping-website:
    name: Ping Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ping Website
        run: |
          chmod +x ping-website.sh
          ./ping-website.sh
        env:
          WEBSITE_URL: https://your-website.com