name: Ping Website

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  ping-website:
    name: Ping Website
    runs-on: ubuntu-latest
    steps:
      - name: Ping Website
        run: echo "Hello World"
        env:
          WEBSITE_URL: https://www.ipm.in-smark.com/